services:
  # ODOO SERVICE (ERP APPLICATION)
  elemento_erp_main:
    image: odoo:18.0
    depends_on:
      - db
    volumes:
      - vol_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./myaddons:/mnt/extra-addons
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    networks:
      - er_erp_net
    restart: always

  # POSTGRESQL DATABASE SERVICE
  db:
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - vol_db_data:/var/lib/postgresql/data/pgdata
    networks:
      - er_erp_net
    restart: always
  
  # NGINX REVERSE PROXY SERVICE (NEW)
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/ # Map the local certificate files to the container's expected path
      - ./certs/server.crt:/etc/ssl/nginx/server.crt:ro
      - ./certs/server.key:/etc/ssl/nginx/server.key:ro
    depends_on:
      - elemento_erp_main # Nginx must wait for Odoo to start
      - db # Nginx must wait for Postgres to start
    networks:
      - er_erp_net
    restart: always

volumes:
  vol_web_data:
  vol_db_data:

networks:
  er_erp_net:
    name: er_erp_net # Crea bridge network con este nombre
