version: '3.7'

services:
  # ODOO SERVICE (ERP APPLICATION)
  elemento_erp_main:
    image: odoo:18.0
    depends_on:
      - db
    # *** IMPORTANT CHANGE: Removed ports mapping (8069:8069) ***
    # Nginx will access Odoo internally via the service name: http://elemento_erp_main:8069
    volumes:
      - vol_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./myaddons:/mnt/extra-addons
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    networks:
      - er_erp_net
    restart: always

  # POSTGRESQL DATABASE SERVICE
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - vol_db_data:/var/lib/postgresql/data/pgdata
    networks:
      - er_erp_net
    restart: always
  
  # NGINX REVERSE PROXY SERVICE (NEW)
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      # Map host ports 80/443 to the container
      - "80:80"
      - "443:443"
    volumes:
      # Mount configuration file (required)
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # Mount Certbot challenge files and certificates for SSL (required for Certbot setup later)
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - elemento_erp_main # Nginx must wait for Odoo to start
    networks:
      - er_erp_net
    restart: always

volumes:
  vol_web_data:
  vol_db_data:

networks:
  er_erp_net:
    name: er_erp_net # Crea bridge network con este nombre
